backend:
  name: github
  repo: dkhole/physio-cms
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: Landing
    label: Landing
    folder: md/landing
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: select, label: Select, widget: select, options: ['title', 'suburb'], required: true }
  - name: Location
    label: Location
    folder: md/location
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, widget: string, label: Title }
      - { name: select, label: Select, widget: select, options: ['address', 'description'], required: true }
  - name: Team
    label: Team
    folder: md/team
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, widget: string, label: Title }
      - { name: select, label: Select, widget: select, options: ['prof1_description', 'prof2_description'], required: true }