backend:
  name: github
  repo: dkhole/physio-cms
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: Landing
    label: Landing
    folder: md/landing
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }